<a href="https://colab.research.google.com/github/NickLarsonUVA/DS1002/blob/main/Assignments/07_More_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More pandas exercises

Create a Colab notebook. Complete the tasks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

1.  Load the following dataset into Colab and perform the requested operations in code.

 Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [5]:
# Load pandas and the data
import pandas as pd
import numpy as np
rideshare = pd.read_csv('./ride_sharing.csv')

In [7]:
# show how many rows and columns are in this dataset
num_rows, num_columns = rideshare.shape
print("rows:", num_rows)
print("columns:", num_columns)

rows: 25760
columns: 10

In [9]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)
rideshare['duration'] = rideshare['duration'].str.strip('minutes')
rideshare['duration'] = rideshare['duration'].astype(int)

In [10]:
# Now display the datatypes in the updated dataframe
rideshare.head(5)

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27

In [17]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.
shortest_ride = rideshare['duration'].min()
longest_ride = rideshare['duration'].max()
print("minimum:", shortest_ride)
print("maximum:", longest_ride)

minimum: 1
maximum: 1372

In [19]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.
new_data = rideshare.query('duration <= 60')
new_data

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27
...,...,...,...,...,...,...,...,...,...,...
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26
25758,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),4438,2,1995,Male,27
25759,29,16,Steuart St at Market St,115,Jackson Playground,1705,3,1990,Male,27

In [20]:
# Now show both the min and max values of the duration column for your new dataset.
shortest_ride_2 = new_data['duration'].min()
longest_ride_2 = new_data['duration'].max()
print("minimum:", shortest_ride_2)
print("maximum:", longest_ride_2)

minimum: 1
maximum: 60

In [22]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.
new_data_2 = new_data.query('tire_size == 26')
new_data_2

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
6,16,67,San Francisco Caltrain Station 2 (Townsend St...,107,17th St at Dolores St,1035,2,1981,Male,26
9,5,30,San Francisco Caltrain (Townsend St at 4th St),62,Victoria Manalo Draves Park,333,1,1994,Male,26
12,7,3,Powell St BART Station (Market St at 4th St),27,Beale St at Harrison St,1863,3,1998,Male,26
...,...,...,...,...,...,...,...,...,...,...
25750,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,4372,2,1994,Male,26
25751,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,5246,1,1995,Male,26
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26

In [30]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.
female_riders = new_data_2.query('user_gender == "FEMALE"')
female_riders = len(female_riders)
female_riders

0

2. Find the file `more-messy-data.csv` on GitHub and upload it into Google Colab.

Create a new Pandas DataFrame from that data and perform the following steps.

In [50]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.
dupes = pd.read_csv('./more-messy-data.csv')
dupes.duplicated()
dupes.duplicated().sum()

287

In [51]:
# Next, remove all duplicate rows using Python.
dupes = dupes.drop_duplicates()
dupes.duplicated().sum() #showing that there are no more duplicates

0

In [52]:
# For the FOUR columns involving sepal and petal length and width, update all NaN
# values with the column mean.
df_drop_all = dupes.dropna()
df_filled = dupes.fillna(dupes.mean())
df_filled

<ipython-input-52-7aae81296b8e>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled = dupes.fillna(dupes.mean())

       id  sepal_length  sepal_width  petal_length petal_width     species
0       1      3.500000      2.90000           1.4         0.5   virginica
1       2      3.600000      3.20000           3.0         0.5      setosa
2       3      3.800000      2.98876           2.2         1.5      setosa
3       4      5.800000      2.70000           2.6         1.2   virginica
4       5      4.900000      3.60000           3.0         1.2   virginica
...   ...           ...          ...           ...         ...         ...
1311  412      4.522004      3.60000           2.9         0.5  Versicolor
1312  413      5.800000      2.70000           2.0         0.1  Versicolor
1313  414      3.300000      3.70000           1.3         2.8  Versicolor
1314  415      3.100000      2.98876           1.1         NaN  Versicolor
1315  416      4.300000      2.50000           1.3           1  Versicolor

[1029 rows x 6 columns]

In [53]:
# Find any values in the dataframe that are still missing, and delete them.
cleaned_data = dupes.dropna()

In [59]:
# How many different species are there?
print(cleaned_data['species'].unique())
num_species = len(cleaned_data['species'].unique())
num_species

['virginica' 'setosa' 'Versicolor' 'setoso' 'Viginica' 'Virginia' 'Setosa'
 'Setosan']

8

In [70]:
# Clean up the 'species' variable so that there are exactly three different values.
mapping = {'Viginica': 'virginica', 'Virginia': 'virginica', 'Setosa': 'setosa', 'setoso': 'setosa', 'Setosan': 'setosa', 'Versicolor': 'versicolor'}
final_data = cleaned_data.replace(mapping)
print(final_data['species'].unique())

['virginica' 'setosa' 'versicolor']

3. Bonus:  Regular expressions

Ordinary (non-vanity) Virginia license plates have the form `ABC1234`, meaning they have three upper case letters followed by four digits.  Write a regular expression that matches any string of this form (and doesn't match anything else).  Test your expression with code to make sure it works.

To figure out out how to do this, start with the sample code below.  The `re` package has various functions related to regular expressions, including for example `match()`, which takes two arguments, first the regular expression and second the test string, and tests to see whether the *beginning* of the `test` string matches the pattern `exp`.

Note that `re.match(exp,test)` does not return a boolean variable, as you might expect (in other words, a match doesn't return `True` and a non-match `False`).  The type of object you get is called `re.Match`, which is a data type special to the `re` package.  (The reason for this is that the object contains more information than just whether there is a match or not.) However, you can turn it into a boolean using `bool()` if you want.

Include the following in the notebook you submit:

 1. A regular expression in a text chunk
 2. One or more code chunks in which you test several strings to verify that your regex is correct.
 3. Make sure you display the results of testing various strings.

 See this [documentation page](https://docs.python.org/3/howto/regex.html#regex-howto) for further help.

In [ ]:
# Sample code for testing whether a string matches a regex

# First import this package for working with regular expressions
import re

# Here is an example.
# Play around with different expressions and test strings to see what happens.
exp = 'ab+'
test = 'aabbbc'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
# print(type(re.match(exp,test)))

# uncomment this line if you want
# print(bool(re.match(exp,test)))